### ISSUE TITLE
vPAV 2.8.0 has (sub-) dependencies that are not available through mvn central

### ISSUE THREAD

**Issue by fkoehne** [viadee/vPAV#104]
**Describe the bug**
vPAV (2.8.0) has (sub-) dependencies (of soot) that are not available through mvn central. Soot itself now has a release build in central, though.

**To Reproduce**
Use or build without access to other repos:
[WARNING] The POM for pxb.android:axml:jar:2.0.0 is missing, no dependency information available
[WARNING] The POM for ca.mcgill.sable:polyglot:jar:2006 is missing, no dependency information available
[WARNING] The POM for heros:heros:jar:1.1.0 is missing, no dependency information available
[WARNING] The POM for ca.mcgill.sable:jasmin:jar:3.0.1 is missing, no dependency information available

**Comment by sdibernardo** [comment]
All dependencies are maintained by the creators of Soot themselves. Already asked for official release versions in mvn central. Hope this will be resolved quickly

**Comment by sdibernardo** [comment]
The following dependencies are required for Soot to work in the context of vPAV

- [ ] pxb.android:axml:jar:2.0.0 (used to create a Scene)
- [ ] ca.mcgill.sable:polyglot:jar:2006
- [ ] heros:heros:jar:1.1.0
- [ ] ca.mcgill.sable:jasmin:jar:3.0.1

**Comment by sdibernardo** [comment]
Resolved with 2.8.1
