### ISSUE TITLE
Prevent build to download artifacts from other repositories

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#108]
As the title says, the build should fail if not all artifacts can be resolved by using only maven central and only release versions.

Check Enforcer Plugin: [Link](https://maven.apache.org/enforcer/enforcer-rules/requireReleaseDeps.html)

**Comment by TamaraGunkel** [comment]
Does that include transitive dependencies or do we only care about the direct dependencies?

**Comment by sdibernardo** [comment]
Includes transitive dependencies :)

**Comment by TamaraGunkel** [comment]
Some (transitive) dependencies seem not to be downloaded from maven central (https://travis-ci.org/viadee/vPAV/builds/520675070#L1134). We should check if it is possible to get rid of them

**Comment by TamaraGunkel** [comment]
I had a closer look at the repositories that are blocked by the enforcer plugin. The plugin ensures that only the defined repositories are used in the Maven session. However, some repositories (like the sonatype or apache repository) are part of the session but are not used for resolving dependencies. I saw that some dependencies define snapshot repositories that become part of the session.
I haven't found a way how to check "real" download path of dependencies. You can see in the travis build that all dependencies are downloaded from Maven central. How important is it to have an automatic check? Any ideas, comments @sdibernardo @fkoehne ?

**Comment by fkoehne** [comment]
Thanks - the priority is largely derived from the priorities of our security-focused users. Let's see if we get more feedback from there.

**Comment by TamaraGunkel** [comment]
@fkoehne Any news on this issue? Is it still important?

**Comment by fkoehne** [comment]
Seems to be safe right now.
