### ISSUE TITLE
Add JIfStmt to JavaReaderStatic

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#122]
JIfStmts are currently not found once source code has been translated to Jimple.
Inclusion would improve accuracy of data flow analysis (around line [694](https://github.com/viadee/vPAV/blob/12de4a30cde39bc1a1f61fa29b28d0899cd65bdc/src/main/java/de/viadee/bpm/vPAV/processing/JavaReaderStatic.java#L694)).

Example:
`if ((Boolean) execution.getVariable("1")) {
        doThis();
  }`

**Comment by fkoehne** [comment]
We just found this new read-Constellation and it might be an opportunity for you to get in touch with this part of the codebase. :)

**Comment by sdibernardo** [comment]
Test results:
`
if ((Boolean) execution.getVariable("1")) { 
doThis(); 
}` results in a NPE if variable can not be found or a casting exception if casted into wrong datatype.

`if (null == execution.getVariable("test")) {
   LOGGER.info("Worked");
}` works properly, does not throw a NPE if variable can not be found and goes into the if block

**Comment by TamaraGunkel** [comment]
It seems as if it was only a temporary issue. A second test conducted by @sdibernardo and myself didn't show this behaviour. The If-statements were converted to assign-statements and therefore validated.
