### ISSUE TITLE
Hierarchy creation fails in certain instances

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#141]
Hierarchy creation for interprocedural calls fails if the recursion goes deeper than 9 calls. Results in NPE during runtime

**Comment by sdibernardo** [comment]
Added test case to ensure that hierarchy creation works properly. Recursion level seems to be irrelevant.

**Comment by fkoehne** [comment]
What is the status here?

**Comment by sdibernardo** [comment]
Fixed with [c32801f](https://github.com/viadee/vPAV/commit/c32801f3c7bd38a312cc1f638e997fac4d7b9b2e)
