### ISSUE TITLE
Support for multi instance tasks

### ISSUE THREAD

**Issue by g-zimmer** [viadee/vPAV#146]
The new data flow analysis feature does not consider multi instance tasks/subprocesses, which loop over collections. See https://docs.camunda.org/manual/7.11/reference/bpmn20/tasks/task-markers/

**Comment by fkoehne** [comment]
... and you are using those in your project, @g-zimmer?

**Comment by g-zimmer** [comment]
Yes, actually quite frequently. In my current customer project, every single process contains multiple multi instance tasks.

**Comment by cl-a-us** [comment]
If we realize this feature, it should provide the following features:
-	Analyze expressions for read operations in variable ‘loopCardinality’, if attribute is specified (e.g. `<loopCardinality>${nrOfOrders-nrOfCancellations}</loopCardinality>` references undefined variables).
-	Read-Operations for the local variables `nrOfInstances`, `nrOfActiveInstances`, `nrOfCompletedInstances` and `loopCounter` do not lead to a UR anomalies.
-	If a collection (attribute ´loopDataInputRef´) is specified, the referenced variable must exist (i.e. prevent UR anomalies, if referenced variable does not exist). Read operations for specified `element variable` (attribute `inputDataItem`) do not lead to an UR anomaly.

@g-zimmer : would this fit your needs?
@TamaraGunkel : could you analyze, if these requirements could be realized with relatively low effort (e.g. by adapting input/output mappings)?

**Comment by g-zimmer** [comment]
@cl-a-us : yes, that would fit our needs (particularly the collection variable check, as we usually iterate over collections).

**Comment by TamaraGunkel** [comment]
Yes, I think if we're using a similiar construct like i/o mapping, it should  be relatively easy to implement. I'll look at this now

**Comment by TamaraGunkel** [comment]
The feature is now included in the development branch. 
@g-zimmer Can you check if it satisfy your needs?
