### ISSUE TITLE
Include whitelisted dependencies

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#149]
Excluding every dependency yields the risk to miss custom written dependencies that access variables throughout the process instance. A whitelist would add those resources to the accessible files and might increase accuracy of the analysis.

**Comment by fkoehne** [comment]
I think we could further limit the depth of the recursive search. Remember that we are looking for access points to the camunda API... transporting this external dependency of a java software through, let's say 10 layers of indirection would be really bad practice. 
On the other hand we want to find bad practice cases specifically. This one should be super rare however.
