### ISSUE TITLE
Test compability with newer versions

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#151]
Check compability with newer versions up to 11

**Comment by sdibernardo** [comment]
Will not be working as long as Soot does not support the targeted versions. Maximum version as of now is Java 9

**Comment by sdibernardo** [comment]
@TamaraGunkel Can you please check what happens if we force vPAV to analyze Java 11 code

**Comment by TamaraGunkel** [comment]
Yes sure, I've already started with that but I'm not yet finished
