### ISSUE TITLE
vPAV-168 As a user I want to see issue-IDs in the modal dialogue, in order to paste it into the ignore-file more easily

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#16]
To easier access the unique issue ID in order to create the .ignoreIssues file

**Comment by fkoehne** [comment]
Maybe should plan this feature more broadly? Maintaining the file is cumbersome. What about a "one-click-Ignore" approach? 
Would this be compatible with the current static-HTML approach? A developer could do this from the IDE and than commit the file. A developer using the Report generated in Jekins probably could not. This may be better represented in a separate issue to discuss a "vision", though.

**Comment by sdibernardo** [comment]
> What about a "one-click-Ignore" approach?
This does not work if we talk about the HTML approach as the browser's sandbox behavior won't let us manipulate files that are lying on the filesystem.

**Comment by fkoehne** [comment]
So this may be a key argument to provide a desktop based tool (additionally) ;)?

**Comment by sdibernardo** [comment]
Yes, as well as the on the fly configuration provided by a GUI. Sounds good :dancer:

**Comment by sdibernardo** [comment]
Unique issue ID is now displayed in the modal

**Comment by fkoehne** [comment]
👍
