### ISSUE TITLE
TimerExpressionChecker can not parse Cycle-Definition with Durations.

### ISSUE THREAD

**Issue by DaZang** [viadee/vPAV#165]
**Problem**
TimerExpressionChecker can not parse Cycle-Definition with Durations like "R11/PT99S".
The called method IsoRecurrence.parseMomentIntervals(String iso) of time4j is made for definitions like "R5/2016-04-01T10:45Z/30T23:59" and time4j does not provide any suitable methods.

**Solution**
Camundas org.camunda.bpm.engine.impl.calendar.DurationHelper offers the desired functionality

I'll create a pull request with a proposed fix and test case

**Comment by sdibernardo** [comment]
Merged the PR. Thanks 👍
