### ISSUE TITLE
As an IT architect I want to validate subprocess calls in order to ensure data is exchanged correctly

### ISSUE THREAD

**Issue by larsbe** [viadee/vPAV#30]
Results of the Delphi study showed that there is great interest into organizing process data. One area, where problem regularly occur, is the call of subprocesses. Usually, the subprocess needs some context of the parent process as input variables. This passing of variables is defined inside the model definition that also implicitly defines the contract between parent process and child process, e.g.:

```
<callActivity id="callSubProcess" calledElement="checkCreditProcess" >
  <extensionElements>
    <camunda:in source="someVariableInMainProcess" target="nameOfVariableInSubProcess" />
    <camunda:out source="someVariableInSubProcss" target="nameOfVariableInMainProcess" />
  </extensionElements>
</callActivity>
```

However, there is no mechanism in place that ensures that the context for the subprocess is correct/sufficient before it is actually called. Especially when migrating the subprocess to a newer version that changes the contract of input/output variables, errors might occur only during runtime.

There are two possible ways to mitigate this problem. First, we could infer the contract of the subprocess' input variables by checking which variables are read before they are written. This feature would build upon [ProcessVariablesModelChecker](https://github.com/viadee/vPAV/blob/master/docs/ProcessVariablesModelChecker.md). But it would be an imperfect solution, as it cannot distinguish between an ill-defined subprocess and an error in calling the subprocess by a parent.

Second, we could make the contract of the call explicit, by defining what variables are to defined as input/output. This feature simply validates the call definition (see above) against the previously defined contract. A downside is that the contract needs to be defined manually by the developer.

This feature could be implemented as an additional checker, as it also outputs validation errors that can be included into the regular result file.

**Comment by fkoehne** [comment]
I would vote for the automatic solution - the manual one introduces more "opportunities" for inconsistencies as well.
This idea is easy to understand and probably feasible as well. I like it.

**Comment by sdibernardo** [comment]
Sounds like a SubProcessChecker is about to be done. I approve that feature as well. Also fits the scope of vPAV

**Comment by fkoehne** [comment]
Done?

**Comment by sdibernardo** [comment]
Will have a look into it (might be already covered due to refactorings)

**Comment by sdibernardo** [comment]
CallActivities are a different story, as In Mapping and Out Mapping have to be transfered to the adjacent elements and additionally the Delegate Variable Mapping needs to be considered. 
Would tag this part as WIP and experimental at this point.

**Comment by sdibernardo** [comment]
Except for the Delegate Variable Mapping, this has been fixed in the latest commits.
