### ISSUE TITLE
Make generating of output optional

### ISSUE THREAD

**Issue by larsbe** [viadee/vPAV#43]
When vPAV is executed on a CI platform (-> jenkins), there is no need to generate all outputs, e.g. HTML that only serves visual purposes.

To speed up the process, there should be a switch to en-/disable generating outputs. 

This issue becomes more important if more visual outputs are generated in the future.

**Comment by sdibernardo** [comment]
Done. HTML output is activated by default and can be overwritten by a rule in the ruleset

**Comment by cl-a-us** [comment]
HTML output is not activated by default in all cases.

An own parent ruleset does not extend on ruleSetDefault.xml. If you use a parent ruleset the output is deactivated by default.

My suggestion: Deactivate output if the value of this specific rule is FALSE. See: [runner.diff.txt](https://github.com/viadee/vPAV/files/2135892/runner.diff.txt)

**Comment by sdibernardo** [comment]
@cl-a-us This usecase is already covered. The hierarchical creation of output is the same as for all rules. By default it is first activated. In case a parent ruleset deactivates this rule, no output will be created, except if the local projects ruleset again sets the value to true. So the behavior is working as expected.
