### ISSUE TITLE
As an IT architect I want to formulate rules with a DSL in order to validate the data flow

### ISSUE THREAD

**Issue by larsbe** [viadee/vPAV#46]
Results of both rounds of the Delphi study showed that there is great interest and potential into automatically validating the data flow of process applications (see #29). Currently vPAV provides a checker ([ProcessVariablesModelChecker](https://github.com/viadee/vPAV/blob/master/docs/ProcessVariablesModelChecker.md)) that validates general errors in manipulating process variables, e.g. reading a variable before it is written. However, data flow rules are very likely to vary across projects/companies apart from these few general cases.

Therefore, to validate the data flow, there needs to be a possibility for the user to formulate his/her own rules against which the data flow is validated. Our idea is to provide a DSL in form of a fluent interface. The fluent interface is supposed to be used in unit tests to formulate rules that are then checked.

Currently, we are evaluating general use cases for such a DSL. To help find these use cases, the main question to ask is: in which scenarios do I want to enforce or restrict the reading/writing/deleting of process variables?

So far we identified four different use cases for this DSL:

- Enfore/restrict reading/writing/deleting of process variables globally, e.g. read-only variables: `processVariables().withPrefix("read-only").should().beWritten().exactly(1)`
- Enfore/restrict scoped reading/writing/deleting of process variables, e.g. read-only variables: `processVariables().withPrefix("confidential").shouldNot().beRead().byModelElements().Except().ServiceTasks().WithProperty("isAllowedToReadConfidentalData")`
- Enforce naming conventions (that are useful to then formulate rules on them, s. read-only variables), e.g. external variables: `processVariables().definedByServiceTasks().should().bePrefixedWith("ext_")`
- Check accessibility of process variables, e.g. `processVariables().withPrefix("confidental").shouldNot().beAccessible().byModelElements().Except().ServiceTasks().WithProperty("isAllowedToReadConfidentalData")`

The last proposed use case has to take the process structure into account. We are not sure yet whether this will be included in the first version of this feature.

We are open and encourage additional suggestions and ideas for the proposed DSL to formulate rules that validate the data flow!

Other aspects open for discussion:
- Provide the possibility to include pre-defined rules in a project (e.g. as Maven dependency).
- We see the visualization of process variable reads/writes as a preliminary step that helps a lot to find and formulate data flow rules. It is also planned to realize the respective issue (see #28).

**Comment by sdibernardo** [comment]
See #57

**Comment by fkoehne** [comment]
I really liked the .because("of reasons") part :).
