### ISSUE TITLE
Validation fails because file can't be written

### ISSUE THREAD

**Issue by larsbe** [viadee/vPAV#48]
Since the commit that added optional generation of HTML output (https://github.com/viadee/vPAV/commit/95ccdf121499d6d63de193cfd5ee2993c39eb866) the validation fails with the following exception:

```
java.lang.RuntimeException: de.viadee.bpm.vPAV.output.OutputWriterException: Effective config file couldn't be generated

	at de.viadee.bpm.vPAV.Runner.readConfig(Runner.java:162)
	at de.viadee.bpm.vPAV.Runner.viadeeProcessApplicationValidator(Runner.java:107)
	at de.viadee.bpm.vPAV.ProcessApplicationValidator.findModelInconsistencies(ProcessApplicationValidator.java:57)
```

Unfortunately the `diff` of the linked commit is somehow broken, so I really can't tell what exactly causes the problem.

There seems to be a problem with generating the directories before writing the files to them (underlying exceptions are `FileNotFoundException` that are thrown when trying to write a file). So to reproduce you might need to remove the target folder first.

**Comment by larsbe** [comment]
Problem persists. I think you still need to create the JS output folder

**Comment by sdibernardo** [comment]
I can not reproduce this on my machine. Can you run mvn clean Install and then proceed with the JUnit test? For me this works fine and mimics the behaviour of the production environment

**Comment by larsbe** [comment]
Did that and still have an exception saying that javascript files couldn't be written.

The issue doesn't occur if I use the previous version. So it has to be caused by something that changed.

**Comment by sdibernardo** [comment]
Will look into it

**Comment by larsbe** [comment]
The above commit fixes the issue for me. But I don't know if that breaks anything.

The hassle we've had strongly suggests some test and/or refactoring :stuck_out_tongue: 

@sdibernardo Close the issue after you've reviewed my commit and think it works that way
