### ISSUE TITLE
As a user, I expect the parent ruleset to extend the default ruleset

### ISSUE THREAD

**Issue by cl-a-us** [viadee/vPAV#55]
Currently a parent ruleset does not extend the default ruleset.
This may cause problems e.g. #43.

Suggestion: 
Extend the tag "ruleSet" with an attribute `extendRuleset={default|none|pathToParent}`. If the attribute is missing, the value should be "default" (extend default ruleset).

**Comment by larsbe** [comment]
Like the idea. I also ran into problems and found it rather suprising that the default behavior is not to extend the default ruleset right now.

**Comment by sdibernardo** [comment]
We discussed it due to #43. 

Actual behavior: 
- Grab all possible vPAV rules (by default deactivated) -> deac. rules
- If a parent ruleset exists, it overwrites the ruleset (deac. rules) 
- The resulting ruleset is then overwritten by the local ruleset

What should be the expected behavior?

**Comment by cl-a-us** [comment]
@sdibernardo, for me the default ruleset is the ruleset that is created if no ruleset is provided. One advantage of having a `extendRuleset` tag is that you can have a chain the inheritance. E.g. A extends B extends C extends default.

**Comment by fkoehne** [comment]
We need a set of examples here...

**Comment by sdibernardo** [comment]
> @sdibernardo, for me the default ruleset is the ruleset that is created if no ruleset is provided. One advantage of having a extendRuleset tag is that you can have a chain the inheritance. E.g. A extends B extends C extends default.

This is exactly the current behavior. If no project-specific ruleset is provided, the default pre-configured ruleset will be activated and used to check the model against. If either a parent-ruleset or a project-specific ruleset is provided, the default ruleset is omitted.

The extension of rulesets is a different discussion. As of now, we can not chain the inheritance except for the parent ruleset. So if we want to provide a chaining mechanism, we need clearly defined rules regarding merging/replacing of rules. 

@fkoehne Example could be a company using company-wide naming conventions (ruleset a). A department within said company could use more fine-grained definition of rules (ruleset B) and within that department a single team could refine said ruleset even more (ruleset C). 

Don't know if that example makes sense, but in a bigger company something alike might occur.

**Comment by fkoehne** [comment]
Thanks. So... we are done here?

**Comment by sdibernardo** [comment]
Regarding the current behavior, I'd say so. If we want to look for a chaining mechanism with multiple rulesets, I suggest to open another issue to have a discussion whether this is needed and feasible.
