### ISSUE TITLE
Architecture Review concerning checker singletons

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#56]
As #52 showed that the creation of singletons led to the wrong output (object of bpmnScanner was wrongly reused). 

Please have a look at #52 and the respective commit, to see the problem. This is a temporary workaround which should be fixed timely.

**Comment by larsbe** [comment]
For me the best solution in this case is to get rid of singletons altogether. I don't see any reason why checkers should be singletons in the first place. It just makes everything more complicated and harder to understand. Feel free to prove me wrong!
