### ISSUE TITLE
Allow a checker to be configured multiple times

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#59]
Thoughts:
- ParentRuleSet -> local RuleSet (change how inheriting works?)
- Declare Checker and provide multiple locations (different classes with different checks?)

Especially for bigger projects, where multiple subprojects might inherit from the same parent ruleset, the local ruleset will overwrite rules that are defined multiple times. Instead of overwriting, merging might be the more intuitive approach here. Additionally, per checker, multiple configurations should be allowed and configurable (extend  XML).

Thoughts? @fkoehne @sebastiansirch @cl-a-us

**Comment by sebastiansirch** [comment]
Regarding inheritance etc., I would prefer to keep things simple: When the child rule set has a rule configured with the same name/id than the parent rule set, the child rule overrides the parent rule completely (without merging any attributes of the rule configuration)

**Comment by sdibernardo** [comment]
@fkoehne That approach looks clean and could be implemented reusing existing logic.

> Regarding inheritance etc., I would prefer to keep things simple: When the child rule set has a rule configured with the same name/id than the parent rule set, the child rule overrides the parent rule completely (without merging any attributes of the rule configuration)

This behaviour is the default case right now. Will still look into it to reassure that it works properly in all cases.

**Comment by sdibernardo** [comment]
What about something like this?
```xml
<rule name="test12">
	<name>JavaDelegateChecker</name>
	<settings>
		<setting></setting>
	</settings>
	<state>true</state>
</rule>
<rule name="test34">
	<name>JavaDelegateChecker</name>		
	<settings>
		<setting></setting>
	</settings>
	<state>true</state>
</rule>

This allows a checker to be configured as often as desired. The logic to instantiate a checker would then change obviously, but I imagine this to be quite intuitive. Does that reflect the need in practice? Inheritance would then work based on the specified rule name as it already does. Any thoughts?
@fkoehne @sebastiansirch

**Comment by fkoehne** [comment]
Works for me.

**Comment by sebastiansirch** [comment]
`	<name>JavaDelegateChecker</name>		
`

Yes, although I think it is a bit confusing to use `<name>` when refering to a Java class or concrete implementation. I would expect something like "className" or "implementation" here.

`<name>` is usually something descriptive, something I can choose more freely, use spaces, special characters etc.; But when this breaks backward compatibility, we should better not change it.

Regarding the new attribute within the rule tag, I would prefer to use "id" over using "name" for a second time, i.e.:
`<rule id="test34">`

Then the logic would be to use "name" as a reference to a checker implementation whereas each instantiation is a rule with a unique "id".
