### ISSUE TITLE
Support for transitive interface implementation

### ISSUE THREAD

**Issue by g-zimmer** [viadee/vPAV#60]
In our customer project, we decided to extract the similarities of delegate classes into abstract classes to avoid redundant code. These abstract classes implement the ExecutionListener/TaskListener/JavaDelegate interface. But every time we run the the vPAV, it shows us inconsistencies because the right interfaces are not implemented - it would be nice, if vPAV could consider the whole class hierarchy.

**Comment by sdibernardo** [comment]
I fully approve that idea as that could be quite common in bigger projects where code is reused.

**Comment by sdibernardo** [comment]
Finally done :) Feedback appreciated

**Comment by fkoehne** [comment]
Yeah! :)
