### ISSUE TITLE
Delegate beans in external JAR are not considered

### ISSUE THREAD

**Issue by g-zimmer** [viadee/vPAV#63]
In projects with several processes, it's quite common to reuse the identical delegate/listener implementation across multiple process applications. Hence, these delegates/listeners are externalized as spring component into a "commons" project, which results in a new JAR artifact. The JAR again is included as dependency in the process application, where the component is injected. Having that situation, running vPAV results in the following error: "Couldn't resolve bean mapping for delegate expression "${commonDelegateXyz}" in "taskListener" - but in fact, the bean is correctly resolved and everyting works fine.

**Comment by fkoehne** [comment]
Thank you for reporting!

**Comment by g-zimmer** [comment]
Ok, it seems that this was just a problem with our spring context configuration. Since we didn't do a component scan on the external jar in our spring __test context__, the delegate component was only found on runtime. I added the component scan for the delegate's package to the test context and it works fine. No issue here!
