### ISSUE TITLE
Refactor map of ProcessVariableOperations to reflect graph structures

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#67]
A Map<String, ProcessVariableOperation> lacks the ability to see the call graph of a variable. Thoughts?

**Comment by fkoehne** [comment]
This is probably useful to simplify the overall structure of our code. We have to graph searches implemented... we only need one, if we integrate java call graphs and process flow in a single model.

**Comment by sdibernardo** [comment]
Done by #103
