### ISSUE TITLE
JavaDelegateChecker cannot resolve @Component-Beans

### ISSUE THREAD

**Issue by kutzilla** [viadee/vPAV#68]
I use an execution listener on a start event with the Listener Type "Delegate Expression". The Delegate Expression I use is `${versionAndKeyExtractListener}`. In my Spring Context I have a class `VersionAndKeyExtractListener` with the `@Component`-Annotation. The process application can easily resolve this bean, based on the annotation. But vPAV reports the following issue:
*Konnte Beanmapping für Delegate Expression '${versionAndKeyExtractListener}' in 'taskListener' nicht auflösen.*

**Comment by sdibernardo** [comment]
After a quick check I found the mistake in the configuration class, which did not inject the delegate properly. After injecting the bean, the delegate expression is resolved correctly by the JavaDelegateChecker.

**Comment by kutzilla** [comment]
Thank you! Closing this issue.
