### ISSUE TITLE
Drop 32-char limit on ignored-Issue display

### ISSUE THREAD

**Issue by fkoehne** [viadee/vPAV#74]
From @sebastiansirch :

> Another aspect: Lines in the ignoredIssues.txt file are cut off after 32 chars which makes this file very hard to read. I don't see a reason why we need to shorten the lines that heavily.
> 
> Example where it is hard to guess the meaning...
> 
> #Element mit ID 'serviceTask_d..
> 123somehashvalues456
> #Element mit ID 'serviceTask_a..
> 123anotherhashvalues456
>

**Comment by fkoehne** [comment]
@larsbe - next week? ;)

**Comment by larsbe** [comment]
@fkoehne Yes, will look into it!
