### ISSUE TITLE
Custom checkers

### ISSUE THREAD

**Issue by aminmc** [viadee/vPAV#77]
Hello

Do custom checkers need to be packaged as a jar? I have a test project and would like to create some custom checkers but the custom checker is being called.

I have created a ruleSet.xml in my test resources folder:
```
<ruleSet>
    <rule>
        <name>FormNameChecker</name>
        <settings>
            <setting name="external_Location">xxx.xxx.xxx.checkers</setting>
        </settings>
        <state>true</state>
    </rule>
</ruleSet>
```
The checker isn't currently being called, even though it's registered.  Is there any specific thing I need to do?

Thanks

**Comment by sdibernardo** [comment]
The rule you specified looks indeed correct. To resolve the external checker, it is mandatory to do run Maven install on said external checker, so it is provided as Jar in your local maven repository (usually .m2 folder). Don't forget to add said package as Maven dependency in your project's pom.xml.

You can also put a breakpoint on line [77](https://github.com/viadee/vPAV/blob/9e65ecbd000ddb77f96357a5d5f94e2aca8f6fe9/src/main/java/de/viadee/bpm/vPAV/processing/checker/CheckerFactory.java#L77) and see if the fully qualified name is resolved properly.  

Best regards
Sascha

**Comment by aminmc** [comment]
Hi there
Thanks for your reply.  It turns I was using an old version, the checker is being registered, however the other default ones are not being registered.  Is there any other config I need to set to include the defaults?

Thanks

**Comment by aminmc** [comment]
Hi @sdibernardo yes I wanted to use the default ones as well.  I tried copy pasting the default ones in my ruleSet but they still come as inactive.  Is there a work around to include the default ones?
There should be option to enable them or perhaps enabled by default and options to exclude?

**Comment by sdibernardo** [comment]
You have two options here: 
- Use the defaultRuleSet.xml only (can not bet altered)
- Use your own ruleSet.xml (defaultRuleSet.xml will be omitted)

If you opt for the second choice, then copy & paste is the way to go and then de-/activate the checkers you want to use. Please be aware, that the files are looked for using case sensitive search inside the class loader. Make sure you really use **ruleSet.xml** and that you put it into the src/test/resources folder inside your project. 

Does the log provide any meaningful information?

**Comment by fkoehne** [comment]
Maybe event automagically? BTW: What does your checker do? If it is a general purpose check we could also solve the inconvenience by including it in the standard set od checkers.

**Comment by aminmc** [comment]
Hey.  It’s a external task topic checker plus I’d like to do a check if someone uses a form it validates against our form engine. 

I think it would be cool for people to had their own specific checkers based on their business functions/requirements. 

Perhaps another approach might be to do a kind of component scanning with an annotation like @Component?

**Comment by sdibernardo** [comment]
> Hey. It’s a external task topic checker plus I’d like to do a check if someone uses a form it validates against our form engine.
> 
> I think it would be cool for people to had their own specific checkers based on their business functions/requirements.

First of all, sorry for the late answer. 
If I understand you correctly, you ask for the capability of vPAV to be able to plug in external checkers, such as your specific checker regarding the usage of forms? This is already doable. Check the documentation [
https://github.com/viadee/vPAV#add-external-checker](url) and also have a look at the provided example. I hope this helps writing and adding your own checkers.

> Perhaps another approach might be to do a kind of component scanning with an annotation like @component?

We will discuss this approach internally and see if this might be beneficial. 
Thanks for your feedback, we highly appreciate it.

Cheers,
Sascha
