### ISSUE TITLE
Support for additional build tools

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#79]
Referencing #77

It would be beneficial to check if additional build tools such as gradle support the execution of vPAV to increase the possible user base. Will look into this issue myself, if it is deemed appropriate.

**Comment by fkoehne** [comment]
This should be working since we mainly rely on the ability to run unit tests.

**Comment by sdibernardo** [comment]
Tested this locally and you can run vPAV from a Gradle/Maven project straight forward.
