### ISSUE TITLE
Configure location of BPMN files

### ISSUE THREAD

**Issue by aminmc** [viadee/vPAV#80]
Currently the framework looks for BPMN in the following src/main/resources, is it possible to make this configurable? In our use case our BPMN are located in a separate project and loaded when our workflow container is created.  Happy to create a PR if this is acceptable?

**Comment by fkoehne** [comment]
Sounds great. What kind of integration are yout thinking about? vPAV is running at unit test-time, i.e. probably before containerization. However, if your container can fetch the model i.e. from a configurable URL it should be as easy to do before the test runs.

**Comment by fkoehne** [comment]
Thanks for your input - can you please tell us more about your experiences with the tool in general? I am interested in what people do with the to, what users find important, like or don't like for our roadmap planning. Thank you!

**Comment by aminmc** [comment]
We're building a central workflow platform and our BPMN files are not located with the engine as this is stored in a separate secured repository.  We would like to run a set of validation tests before the BPMN files are uploaded into the engine using CI.  The semantic validation is extremely useful for us as it gives us an opportunity to validate the BPMNs before loaded into the engine.  We would also like the ability to create custom validators based on our business uses cases.

Hope this helps.
